### ISSUE TITLE
Support torbot data collection 

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/gotor#46]
Gotor needs to be extended to support the collect data process of torbot

https://github.com/DedSecInside/TorBot/issues/272

**Comment by Chaddaigo** [comment]
Meed a help on how to get a private link on a sender wallet not a dormant wallet the sender wallet I have the Transaction hash and also the signature of the sender

**Comment by KingAkeem** [comment]
@Chaddaigo That's not the purpose of this project or ticket so I can't assist you there. There are other projects more suited for what you're trying to accomplish.

**Comment by KingAkeem** [comment]
No longer relevant
